# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Motorsjungle123!
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: motorsjungle_development

test:
  <<: *default
  database: motorsjungle_test

production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
